Adds Optional Links to Content Overrides
swedenconnect/bankid-saml-idp pull request #117
Opened 2023-09-20 12:40 UTC by felix-hellman

<img width="677" alt="Screenshot 2023-09-20 at 14 36 25" src="https://github.com/swedenconnect/bankid-saml-idp/assets/12511470/5252a9d0-9a04-468d-82d3-0434e1d5f2ab">

This is working but I had to do some ugly hacks in frontend to get everything to align properly @oestrogen maybe you can improve on my non-optimal solution?

2023-09-20 12:55 UTC, martin-lindstrom requested changes

2023-09-20 12:55 UTC, martin-lindstrom commented on bankid-idp/env/local/overrides/custom.messages
> +      "sv": "Skaffa Test BankID",
Ändra till "Skaffa BankID för test". Annars blir det en särskrivning. Vi använder inte heller camel-case på svenska.
/Petig

2023-09-20 12:55 UTC, martin-lindstrom commented on docs/override.md
> +You can also include links in the alert boxes
end with ':'.

2023-09-20 12:55 UTC, martin-lindstrom commented on docs/override.md
>  ```json
Should also state that each content element will become a paragraph in the alert box ...

2023-09-20 14:19 UTC, oestrogen commented
I fixed the styling and also added back the dot-files for ESLint and Prettier that where lost in the restructuring.

2023-09-20 14:19 UTC, oestrogen approved these changes

2023-09-21 07:17 UTC, martin-lindstrom approved these changes

2023-09-21 07:17 UTC, merged